import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.84.0';
import { corsHeaders } from '../_shared/cors.ts';

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { story_id, platform = 'instagram' } = await req.json();

    if (!story_id) {
      return new Response(
        JSON.stringify({ error: 'story_id is required' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const lovableApiKey = Deno.env.get('LOVABLE_API_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    console.log(`[generate-post-image] Generating image for story ${story_id}, platform ${platform}`);

    // Fetch story metadata
    const { data: story, error: fetchError } = await supabase
      .from('content_queue')
      .select('id, title, category, summary, content')
      .eq('id', story_id)
      .single();

    if (fetchError || !story) {
      console.error('[generate-post-image] Story not found:', fetchError);
      throw new Error('Story not found');
    }

    // Build prompt for AI image generation
    const prompt = buildImagePrompt(story, platform);
    console.log('[generate-post-image] Prompt:', prompt);

    // Call Lovable AI Gateway to generate image
    const aiResponse = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${lovableApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash-image-preview',
        messages: [
          {
            role: 'user',
            content: prompt,
          },
        ],
        modalities: ['image', 'text'],
      }),
    });

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      console.error('[generate-post-image] AI API error:', aiResponse.status, errorText);
      throw new Error(`AI API error: ${aiResponse.status}`);
    }

    const aiData = await aiResponse.json();
    const imageBase64 = aiData.choices?.[0]?.message?.images?.[0]?.image_url?.url;

    if (!imageBase64) {
      console.error('[generate-post-image] No image in AI response:', JSON.stringify(aiData));
      throw new Error('No image generated by AI');
    }

    console.log('[generate-post-image] Image generated, uploading to storage...');

    // Convert base64 to blob
    const base64Data = imageBase64.replace(/^data:image\/\w+;base64,/, '');
    const imageBytes = Uint8Array.from(atob(base64Data), c => c.charCodeAt(0));

    // Upload to Supabase Storage
    const fileName = `${story.id}-${platform}-${Date.now()}.png`;
    const filePath = `lake-geneva/${story.category || 'general'}/${fileName}`;

    const { data: uploadData, error: uploadError } = await supabase.storage
      .from('generated-images')
      .upload(filePath, imageBytes, {
        contentType: 'image/png',
        cacheControl: '3600',
        upsert: false,
      });

    if (uploadError) {
      console.error('[generate-post-image] Upload error:', uploadError);
      throw uploadError;
    }

    // Get public URL
    const { data: urlData } = supabase.storage
      .from('generated-images')
      .getPublicUrl(filePath);

    const publicUrl = urlData.publicUrl;
    console.log('[generate-post-image] Image uploaded:', publicUrl);

    return new Response(
      JSON.stringify({
        success: true,
        image_url: publicUrl,
        story_id: story.id,
        platform,
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  } catch (error) {
    console.error('[generate-post-image] Fatal error:', error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : 'Unknown error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});

function buildImagePrompt(story: any, platform: string): string {
  const categoryStyles: Record<string, string> = {
    events: 'community gathering, celebration, people enjoying activities',
    dining: 'food, restaurant ambiance, culinary presentation',
    community: 'neighborhood, local gathering, people connecting',
    news: 'professional, newsworthy, local landmark',
    'real-estate': 'homes, architecture, lakeside properties',
  };

  const style = categoryStyles[story.category] || 'warm community atmosphere, local charm';

  return `Create a clean, modern social media image for a local Lake Geneva community post.

Topic: ${story.title}
Category: ${story.category || 'general'}
Summary: ${(story.summary || story.content)?.substring(0, 200)}

Style: Warm, family-friendly, community feel with ${style}. 
Lake Geneva aesthetic: lakeside town, cozy, upscale yet accessible.
Modern and clean design.
No text overlay. No logos. No people's faces.
1024x1024 square format optimized for ${platform}.`;
}
